all:
  children:
    central:
      hosts:
        tooling:
          ansible_host: 192.168.5.10
    workers:
      children:
        amd64:
          hosts:
            china4:
              ansible_host: 192.168.5.44
              architecture: amd64
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/homelab_ansible
    network_subnet: 192.168.5.0/24
    network_gateway: 192.168.5.1
