# MASTER PLAYBOOK
---
- hosts: all
  become: yes
  roles:
    - role: common

# If the host has containers assigned, it must then have docker installed
- hosts: all
  roles:
    - role: docker
  tags: docker
