containers: []
docker_services: {}
tz: "Europe/Madrid"

docker_volumes_path: "/var/docker_volumes"
docker_config_path: "/srv/docker"
python_system_venvs_path: "/srv/python_venvs"

docker_services_mongo:
  - name: "mongodb"
    image: "mongo"
    tag: "latest"
    ports:
      - "80:80"
    volumes:
      - "/data": "/data"
    env:
      ENV_VAR1: "value1"