##
# OS
##
# Pubkeys to add to the ansible admin user. Not really a secret.
ansible_admin_pub_keys: "{{ vault_ansible_admin_pub_keys }}"
admin_pub_keys: "{{ vault_admin_pub_keys }}"

admin_user_password: "{{ vault_admin_user_password }}"
email_password: "{{ vault_email_password }}"
db_password: "{{ vault_db_password }}"

web_admin_password: "{{ vault_web_admin_password }}"

# Encryption keys
semaphore_key: "{{ vault_semaphore_key }}"
healthchecks_key: "{{ vault_healthchecks_key }}"

cloudflare_homelab_token: "{{ vault_cloudflare_homelab_token }}"
