---
- name: Create user
  user:
    name: "{{ user.username }}"
    shell: /bin/bash
    state: present
    home: "/home/{{ user.username }}"

- name: allow admin user to have passwordless sudo
  lineinfile:
    path: "/etc/sudoers.d/{{ user.username }}"
    line: "{{ user.username }} ALL=(ALL) NOPASSWD: ALL"
    # Older systems require this to be 0440 or sudo breaks.
    mode: 0440
    create: yes
    validate: /usr/sbin/visudo -cf %s
  when: "not user.allow_password"

- name: Add SSH keys for the user
  authorized_key:
    user: "{{ user.username }}"
    key: "{{ item }}"
    state: present
  loop: "{{ user.ssh_keys | list}}"

- name: User groups
  group:
    name: "{{ item }}"
  loop:
    - software
    - docker

- name: Admin groups
  user:
    name: "{{ user.username }}"
    groups:
      - sudo
      - software
      - docker
    append: yes

- name: Symbolic link for tmp
  ansible.builtin.file:
    dest: "/home/{{ user.username }}/tmp"
    src: /tmp
    owner: "{{ user.username }}"
    group: "{{ user.username }}"
    follow: false
    state: link

- name: Create symbolic link for opt
  ansible.builtin.file:
    dest: "/home/{{ user.username }}/software"
    src: /opt
    owner: "{{ user.username }}"
    group: "{{ user.username }}"
    follow: false
    state: link

- name: Configure /opt directory
  ansible.builtin.file:
    path: /opt
    state: directory
    owner: root
    group: software
    mode: "02775"


- name: Ensure .ssh directory exists.
  file:
    dest: "/home/{{ user.username }}/.ssh"
    mode: 0700
    owner: "{{ user.username }}"
    state: directory

- name: Copy backup key
  ansible.builtin.copy:
    content: "{{ vault_nas_backup_key }}"
    dest: "/home/{{ user.username }}/.ssh/homelab_backup"
    owner: "{{ user.username }}"
    mode: 0700

- name: Add known hosts
  ansible.builtin.copy:
    content: "{{ known_hosts }}"
    dest: "/home/{{ user.username }}/.ssh/known_hosts"
    owner: "{{ user.username }}"
    mode: 0600

# This must be after setting up passwordless sudo and the authorized_keys.
- name: remove admin password
  user:
    name: "{{ user.username }}"
    password: "*"
