---

- name: Set interface name
  set_fact:
    interface: "{{ ansible_default_ipv4.interface }}"


- name: Netplan
  block:
    - name: Generate netplan configuration file
      template:
        src: netplan_config.yml.j2
        dest: /etc/netplan/01-netcfg.yaml
        mode: '0600'
      register: netplan_change

    - name: Remove
      file:
        path: /etc/netplan/50-cloud-init.yaml
        state: absent
      register: netplan_change

    - name: Apply network changes
      command: netplan apply
      when: netplan_change is changed


  when: ansible_distribution == 'Ubuntu'


- name: Interfaces
  block:
    - name: Generate config configuration file
      template:
        src: 01-main.j2
        dest: /etc/network/interfaces.d/01-netcfg
        mode: '0644'
      register: interfaces_change

    - name: Apply network config
      when: interfaces_change.changed
      shell: "ip addr flush dev {{ interface }}"
  when: ansible_distribution_release == "bullseye"
