---

- name: Set docker compose location
  ansible.builtin.set_fact:
    docker_compose_location: "{{ docker_config_path }}/{{ compose_name }}/docker-compose.yml"

- name: Ensures docker folder for service exists
  file:
    path: "{{ docker_config_path }}/{{ compose_name }}"
    state: directory

- name: Create docker-compose file from template
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_compose_location }}"
  register: compose_file
  
- name: Check if any containers are running for the Docker Compose project
  ansible.builtin.command: "docker compose -f {{ docker_compose_location }} ps -q"
  register: docker_ps_output

- name: Parse running containers count
  set_fact:
    running_containers: "{{ docker_ps_output.stdout_lines | list | length}}"

- name: Execute action if any containers are running
  ansible.builtin.debug:
    msg: "Running containers: {{ running_containers }}"


- name: Pull latest images
  command: "docker compose -f {{ docker_compose_location }} pull"
  when: compose_file.changed or running_containers == "0"

- name: Stop services
  command: "docker compose -f {{ docker_compose_location }} down -t 120"
  when: compose_file.changed or running_containers == "0"

- name: Deploy the services if not up-to-date
  command: "docker compose -f {{ docker_compose_location }} up -d"
  when: compose_file.changed or running_containers == "0"
