# This is not meant to be called in a standalone maner (note that we dismo unt the backup)
---
- name: Backup docker volumes
  tags: backup
  block:
  - name: Mount NFS backup share
    ansible.builtin.include_role:
      name: common
      tasks_from: mount_util
    vars:
      do_mount:
        mount: "backups"
        state: "mounted"

  - name: Do backup
    ansible.posix.synchronize:
      src: "{{ docker_volumes_path }}/"
      dest: "{{ nas.backups.mount_point }}/docker/"
    delegate_to: "{{ inventory_hostname }}"

  always:
  - name: Mount NFS backup share
    ansible.builtin.include_role:
      name: common
      tasks_from: mount_util
    vars:
      do_mount:
        mount: "backups"
        state: "unmounted"
