# Base from https://medium.com/@GarisSpace/how-to-install-docker-using-ansible-01a674086f8c modified as per
# official docker documentation
---
- name: Install docker with admin
  block:
    - name: Update and upgrade all packages to the latest version
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install required packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common

    - name: Create directory for Docker's GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/keyrings/docker.gpg
        state: present

    - name: Print architecture variables
      ansible.builtin.debug:
        msg: "Architecture: {{ ansible_architecture }}, Codename: {{ ansible_lsb.codename }}"

    - name: Add Docker repository and update ppa if neccessary
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch={{ arch_mapping[ansible_architecture] | default(ansible_architecture) }}
          signed-by=/etc/apt/keyrings/docker.gpg]
          https://download.docker.com/linux/{{ ansible_distribution | lower}} {{ ansible_lsb.codename }} stable
        filename: docker
        update_cache: true
        state: present


    - name: Install Docker and related packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

    - name: Add Docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add users to Docker group
      ansible.builtin.user:
        name: "{{ item }}"
        groups: docker
        append: true
      loop:
        - "{{ ansible_user }}"
        - "{{ username }}"

    - name: Enable and start Docker services
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - docker.service
        - containerd.service
    - name: Create virtual environment for docker
      file:
        path: "{{ docker_venv }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: software
        recurse: true
        mode: "02775"
  become: yes

- name: Create python docker venv
  ansible.builtin.pip:
    name:
      - wheel
      - setuptools
    virtualenv: "{{ docker_venv }}"

- name: Enable python integration
  ansible.builtin.pip:
    name:
      - pyyaml==5.4.1
      - cython<3.0.0
      - docker==6.1.3
      - docker-compose
    virtualenv: "{{ docker_venv }}"
    extra_args: "--no-build-isolation"

- name: ensures {{ docker_config_path }} dir exists
  become: yes
  file:
    path: "{{ docker_config_path }}"
    recurse: yes
    state: directory
