---

# It expects the facts:
# compose_name: docker_compose name
# docker_service: docker service struct

- name: docker_service
  debug:
    var: "docker_service"

- name: Create docker volumes root folder
  become: yes
  file:
    path: "{{ docker_volumes_path }}/{{ compose_name }}"
    recurse: yes
    state: directory

- name: Check if each volume directory exists
  stat:
    path: "{{ docker_volumes_path }}/{{ compose_name }}/{{ volume_name }}"
  loop: "{{ docker_service.volumes.keys() }}"
  loop_control:
    loop_var: volume_name
  register: volume_names

- name: Create dirs for volumes
  become: yes
  file:
    path: "{{ docker_volumes_path }}/{{ compose_name }}/{{ volume_name }}"
    state: directory
  loop: "{{ docker_service.volumes.keys() }}"
  loop_control:
    loop_var: volume_name


- name: Create dirs for volumes backups  # This will prevent rsync from failing when not found
  become: yes
  file:
    path: "{{ nas.backups.mount_point }}/docker/{{ compose_name }}/{{ volume_name }}"
    state: directory
  loop: "{{ docker_service.volumes.keys() }}"
  loop_control:
    loop_var: volume_name

- name: Restore backup if present
  ansible.posix.synchronize:
    src: "{{ nas.backups.mount_point }}/docker/{{ compose_name }}/{{ volume }}/"
    dest: "{{ docker_volumes_path }}/{{ compose_name }}/{{ volume }}/"
  when:
    - not volume_names.results[item_index].stat.exists
  loop: "{{ docker_service.volumes.keys() }}"
  delegate_to: "{{ inventory_hostname }}"
  loop_control:
    index_var: item_index
    loop_var: volume
