---
- name: Check if the volume directory exists
  stat:
    path: "{{ item.split(':')[0] }}"
  loop: "{{ docker_service.volumes }}"
  register: volume_dirs

- name: Copy backup data if volume doesn't exist and backup is available
  copy:
    src: "{{ docker_service.backup_folder }}/"
    dest: "{{ item.split(':')[0] }}/"
    remote_src: yes
  when:
    - not volume_dirs.results[item_index].stat.exists
    - docker_service.backup_folder is defined
  loop: "{{ docker_service.volumes }}"
  loop_control:
    index_var: item_index
