native_services: []


# MongoDB
mongodb_tag: "7.0-ubuntu2204"
mongodb_user: "mongo"
mongodb_password: "{{ db_password | default('') }}"
mongodb_volume_local_path: "{{ docker_volumes_path }}/mongodb"

persistent_network_mounts:
  - homelab
temporal_network_mounts:
  - backup

containers:
  - mongodb
  - nexus
  - mlflow
  - uptimekuma

docker_services:
  mongodb:
    - name: "mongodb"
      image: "mongo"
      tag: "8-noble"
      ports:
        - "27017:27017"
      volumes:
        mongodb_volume: "/data/db"
      env:
        MONGO_INITDB_ROOT_USERNAME: "{{ mongodb_user }}"
        MONGO_INITDB_ROOT_PASSWORD: "{{ mongodb_password }}"
  uptimekuma:
    - name: "uptimekuma"
      image: "louislam/uptime-kuma"
      tag: "1.23.15-alpine"
      ports:
        - "4030:3001"
      volumes:
        uptimekuma_data: "/app/data"
  nexus:
    - name: "nexus"
      image: "sonatype/nexus3"
      tag: "3.77.1-alpine"
      ports:
        - "8081:8081"
        - "8085:8085"
      volumes:
        nexus_data: "/nexus-data"

  mlflow:
    - name: "mlflow"
      image: "bitnami/mlflow"
      tag: "2.20.1"
      ports:
        - "8082:8081"
        - "8084:8085"
      volumes:
        nexus_data: "/nexus-data"
